djangoCMSProject/authentication/urls.py
from django.urls import path

from .views import login_template, register_template, handle_login, handle_signup, handle_logout

app_name = "authentication"

urlpatterns = [
    path("", login_template, name="loginPage"),
    path("login/", handle_login, name="login"),
    path("signup/", register_template, name="signupPage"),
    path("register/", handle_signup, name="register"),
    path("logout/", handle_logout, name="logout")
]

djangoCMSProject/djangoCMSProject/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path("auth/", include("authentication.urls")),
    path('', views.viewPage, {'slug': ''}, name="pages-root"),
    path("<slug:slug>", views.viewPage, name="pages-details-by-slug"),
    path("add-page-form/", views.AddPageForm, name="add-page-form"),
    path("add-page/", views.handleAddPageRequest, name="handleAddPageRequest"),
]

djangoCMSProject/authentication/models.py
from django.db import models

# Create your models here.

djangoCMSProject/cms_integration/models.py
from django.db import models
from cms.models import CMSPlugin
# Create your models here.

djangoCMSProject/authentication/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User


def login_template(request):
    if request.method == "GET":
        return render(request, "login.html")


def register_template(request):
    return render(request, "register.html")


@csrf_protect
def handle_login(request):
    try:
        if request.method == "POST":
            if not request.user.is_authenticated:
                username, password = request.POST['username'], request.POST['password']
                user = authenticate(
                    request, username=username, password=password)
                if user is not None:
                    login(request, user)
                    return redirect("/")
                else:
                    return HttpResponse('Invalid User')
            else:
                return HttpResponse('Already Logged In')
    except Exception as error:
        return HttpResponse("{0}".format(error))


@csrf_protect
def handle_signup(request):
    try:
        if request.method == "POST":
            first_name, last_name, username, password = request.POST['first_name'], request.POST[
                'last_name'], request.POST['username'], request.POST['password']
            if request.user.is_authenticated:
                return redirect("/")

            if not User.objects.filter(username=username).exists():

                user = User.objects.create_user(
                    username=username, email=username, password=password)
                user.first_name = first_name
                user.last_name = last_name
                user.is_active = True
                user.is_superuser = False
                user.is_staff = False
                user.save()
                return redirect('authentication:loginPage')
            else:
                return HttpResponse('User already exists')
    except Exception as error:
        return HttpResponse("{0}".format(error))


def handle_logout(request):
    try:
        if request.user.is_authenticated:
            logout(request)
            return redirect("/")
    except Exception as error:
        return HttpResponse("{0}".format(error))

djangoCMSProject/cms_integration/views.py
from django.shortcuts import render

# Create your views here.

djangoCMSProject/djangoCMSProject/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.template.defaultfilters import slugify
from django.contrib.auth.decorators import login_required
from django.core import exceptions

from cms.utils import get_current_site
from cms.models.pagemodel import TreeNode
# from cms.utils.conf import get_cms_setting
from cms.utils.page_permissions import user_can_change_page
from cms.api import create_page, add_plugin
from cms import constants

from djangoCMSProject.utils.index import getPageTemplate, get_page_from_request, duplicate_slug_check


def viewPage(request, slug):
    try:
        site = get_current_site()  # Return current site in form of domain.
        page = get_page_from_request(request, use_path=slug)  # Return Page

        # # Check If nodes are available in site.
        treeNodes = TreeNode.objects.get_for_site(site)

        if not page and not slug and not treeNodes.exists():
            # No page|Slug|No Node is available then render welcome page
            # welcome.html is not available yet.
            return render(request, template_name="page/welcome.html")

        if not page:
            # no_page.html is not available yet.
            # raise exceptions.BadRequest('Page Doesnot Exists.')
            return render(request, template_name="page/no_page.html")

        if page.login_required and not request.user.is_authenticated():
            return redirect("authentication:login")

        template = getPageTemplate(manual_template=None, page_id=page.id)
        return render(request, template)

    except Exception as Error:
        return HttpResponse("Exception has been raised.{0}".format(Error))


def AddPageForm(request):
    return render(request, "page/add.html")


def handleAddPageRequest(request):
    try:
        if (request.method == "POST"):
            title, menu_title, isPagePublished, page_content = request.POST["title"], request.POST[
                "menu-title"], request.POST.getlist("isPagePublished"), request.POST["page-content"]

            slug = slugify(title)
            if not slug:
                raise exceptions.FieldError("Slug cannot be empty .")

            if not duplicate_slug_check(slug):
                return HttpResponse("Invalid Slug.")

            menu_title = menu_title.lower()
            template = getPageTemplate()
            published = True if isPagePublished[0] == 'true' else False
            site = get_current_site()
            language = 'en'
            pluginType = 'TextPlugin'
            newPage = create_page(title=title, template=template, language=language, menu_title=menu_title,
                                  slug=slug, apphook=None, apphook_namespace=None, redirect=None, meta_description=None, created_by='python-api', site=site, published=published, login_required=False,
                                  limit_visibility_in_menu=constants.VISIBILITY_ALL,
                                  position='first-child')

            # No need to add IF condition as we are not including log-in functionality

            # if request.user.is_authenticated and newPage.placeholders.has_add_plugin_permission(User):
            placeholders = newPage.placeholders.get(slot='content')

            # if newPage.placeholders.has_add_plugin_permission(User):
            add_plugin(placeholders, pluginType, language, body=page_content)
    except exceptions.FieldError as field_error:
        return HttpResponse("{0}".format(field_error))
    except Exception as error:
        return HttpResponse("{0}".format(error))
    else:
        return redirect("/")


@login_required
def editPageContent(request, slug):
    # In Web content editing mode.
    if request.user.is_authenticated():
        page = get_page_from_request(request, use_path=slug)
        if user_can_change_page(request.user, page):
            # User can edit this page.
            pass

        else:
            print("User didn't has permissions to edit the page content.")
            return HttpResponse("User didn't has permissions to edit the page content.")

djangoCMSProject/authentication/templates/login.html
{% extends 'layout/layout.html' %}
{% load cms_tags %}
{% block content %}

<div class="login-div m-5 p-3 w-50" style="border:1px solid lightgrey;border-radius:5px">
   <div class="text-center"><h3>Login</h5></div>
   <form method="POST" action={% url 'authentication:login' %}>
     {% csrf_token %}
     <div class="mb-3">
       <label for="username" class="form-label">Email<span style="color:red">*</span></label>
       <input type="email" class="form-control" id="username" name="username" aria-describedby="emailHelp">
     </div>
     <div class="mb-3">
       <label for="password" class="form-label">Password<span style="color:red">*</span></label>
       <input type="password" class="form-control" id="password" name="password">
     </div>          
     <button type="submit" class="btn btn-success float-left">Submit</button>
     <div class="my-3">
       <span>Don't have account <a href={% url 'authentication:signupPage'%}>Sign-Up</a></span>
     </div>
     
   </form>
</div>
{% endblock content %}

djangoCMSProject/authentication/templates/register.html
{% extends 'layout/layout.html' %}
{% load cms_tags %}
{% block content %}

<div class="login-div m-5 p-3" style="border:1px solid lightgrey;border-radius:5px">
   <div class="text-center"><h3>SignUp</h5></div>
   <form method="POST" action={% url 'authentication:register'%}>
   {% csrf_token %}
   <div class="mb-3">
      <label for="first_name" class="form-label">First Name<span style="color:red">*</span></label>
      <input type="text" class="form-control" id="first_name" name="first_name" aria-describedby="first_nameHelp">
   </div>
   <div class="mb-3">
      <label for="last_name" class="form-label">Last Name<span style="color:red">*</span></label>
      <input type="text" class="form-control" id="last_name" name="last_name" aria-describedby="last_nameHelp">
   </div>
   <div class="mb-3">
      <label for="username" class="form-label">Email<span style="color:red">*</span></label>
      <input type="email" class="form-control" id="username" name="username" aria-describedby="emailHelp">
   </div>
   <div class="mb-3">
      <label for="password" class="form-label">Password<span style="color:red">*</span></label>
      <input type="password" class="form-control" id="password" name="password">
   </div>          
   <button type="submit" class="btn btn-success float-left">Submit</button>
   <div class="my-3">
      <span>Already have an account <a href="{% url 'authentication:loginPage' %}">Login</a></span>
   </div>
   </form>
</div>


{% endblock content %}

djangoCMSProject/djangoCMSProject/templates/fullwidth.html
{% extends './layout/layout.html' %}
{% load cms_tags %}

{% block title %}
   {% page_attribute "page_title" %}
{% endblock title %}

{% block content %}
   <div class="web-content" id="web-content">
      {% if request.user.is_authenticated %}
         <input type="hidden" name="authenticatedUser" id="authenticatedUser" value='{{request.user.is_authenticated}}'/> 
         <a href="" role="button" class="btn btn-warning">
            Save
         </a>
         <br/>
      {% endif %}
      {% placeholder "content" %}
      
   </div>

   <script>
      const isUserAuthenticated = document.getElementById("authenticatedUser").value
      if (isUserAuthenticated == "True"){
         ClassicEditor
         .create( document.querySelector( '#web-content' ) )
         .catch( error => {
             console.error( error );
         } );
      }
   </script>

{% endblock content %}

djangoCMSProject/djangoCMSProject/templates/index.html
{% extends 'layout/layout.html' %}

{% block content %}
   <ul class="nav nav-tabs" id="navId">
      {% for page_data in data %}
         <li class="nav-item">
            <a href="/{{page_data.path}}" class="nav-link">{{page_data.menu_title}}</a>
         </li>
      {% endfor %}
   </ul>
   <a href={% url 'add-page-form' %} role="button" class="btn btn-outline-success">
      Add Page
   </a>
{% endblock content %}

djangoCMSProject/djangoCMSProject/templates/layout/layout.html
{% load cms_tags menu_tags %}

<!DOCTYPE html>
<html>
   <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <title>{% block title%}{% endblock title%}</title>
      <meta name="description" content="">
      <meta name="viewport" content="width=device-width, initial-scale=1">      
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
      <script src="https://cdn.ckeditor.com/ckeditor5/36.0.1/classic/ckeditor.js"></script>
      <style type="text/css">
         .nav {
            padding-left: 0;
        }
        .nav li {
            display: inline;
            list-style-type: none;
            padding-right: 20px;
        }
      </style>
   </head>
   <body>
      <div class="container p-3">
         <ul class="nav">
            {% show_menu %}
            <li>
               <a href={% url 'add-page-form' %} role="button" class="btn btn-outline-success">
                  Add Page
               </a>
            </li>
            
            {% if request.user.is_authenticated %}
               <li>
                  Hello {{request.user.first_name}} {{request.user.last_name}}
                  <a href={% url 'authentication:logout' %} role="button" class="btn btn-danger">Logout</a>
               </li>
            {% else %}
               <li>
                  <a href={% url 'authentication:loginPage' %} role="button" class="btn btn-outline-success">
                     Login
                  </a>
               </li>
            {% endif %} 
         </ul>
         <div class="my-3">
            {% block content %}
            {% endblock content %}
         </div>
      </div>
   </body>
</html>

djangoCMSProject/djangoCMSProject/templates/page/add.html
{% extends '../layout/layout.html' %}

{% block content %}
   <div class="add-page-form p-3">
      <h4>New Page</h4>
      <form method="post" action={% url 'handleAddPageRequest' %}>
         {% csrf_token %}
         <div class="form-group my-1 ">
            <label for="title" class="my-1">Title</label>
            <input type="text"
            class="form-control" name="title" id="title" aria-describedby="title">
         </div>
         <div class="form-group my-1">
            <label for="menu-title" class="my-1">Menu Title</label>
            <input type="text" class="form-control" name="menu-title" id="menu-title" aria-describedby="helpId"/>
         </div>
         <div class="form-check form-check-inline my-2">
            <span class="mx-3">
               <label class="form-check-label">
                  <input class="form-check-input" type="checkbox" name="isPagePublished" id="publishPageTrue" value="true"> 
               </label>Publish Page
            </span>
            <span class="mx-3">
               <label class="form-check-label">
                  <input class="form-check-input" type="checkbox" name="isPagePublished" id="publishPageFalse" value="false"> 
               </label>Do not Published Page
            </span>      
         </div> 
         <div class="form-group my-1">
            <label for="page-content" class="my-1">Page Content</label>
            <textarea class="form-control" name="page-content" id="page-content" rows="3"></textarea>
         </div>
         <div class="text-center my-3">
            <button type="submit" class="btn btn-success w-25">Add</button>
         </div>
      </form>
   </div>
{% endblock content %}